### ISSUE TITLE
Small note if you're trying to test out rust

### ISSUE THREAD

**Issue by Alxandr** [AArnott/guessing_game.rs#1]
Hi. Sorry to bug you in a repo that's probably just you trying rust out (it just showed up in my GH feed) - I just wanted to note that the `rust-lang.rust` extension is mostly deprecated at this point and https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer is the one you should really be trying if you want to get the best experience programming rust. You can see some more info about it here: https://www.reddit.com/r/rust/comments/uoq73y/the_rustanalyzer_vscode_extension_is_now/.

**Comment by AArnott** [comment]
Yes, this is me just trying out rust. But I'll take all learnings wherever I can get it, especially in rust. Thank you.

**Comment by Alxandr** [comment]
No problem. It definitely has a learning curve. And having the older IDE integration that's not really maintained anymore as what shows up by default when searching in VS code is definitely a stumbling block that's unfortunate.

Do note that you need to uninstall the old extension as well as installing the new one (as they both fight for `.rs` files if not).

Also, if you have any questions or would like some review, feel free to poke me :).

**Comment by AArnott** [comment]
Well, here is my first "real" attempt at a rust library: https://github.com/AArnott/Nerdbank.Algorithms.rs

Your critique is most welcome. The C# to rust conversion is only perhaps 25% done, excluding tests.

**Comment by Alxandr** [comment]
Leaving some short notes right now (as that's all I have time for at the moment) - but will try to remember to get back to it when I have better time ;).

First simple thing, in rust 2018 and newer, you don't need this:

```rs
#[macro_use]
extern crate bitflags;
```

Instead, just `use bitflags::bitflags` (or `bitflags::bitflags!`) where you need it. Cargo will generate the `extern crate` for you, and `#[macro_use]` is mostly superflous.

Second, traits starting with a capital `I` like an interface in C# is definitely a smell I think :P. I would just call your `IConstraint` trait as `Constraint`.

The last point I noticed is that you've used const generics for the size of your "experiment" (and some of the other types). This is fine (and can be really usefull if you're doing it for performance reasons) - but the effect is that the entire array is kept on the stack (ie, you can much more easily blow your stack - think stackalloc in C#). If you didn't mean for this to be the case, just go with `Vec` instead.

**Comment by AArnott** [comment]
Thanks. I'll update the bitflags.
The traits naming convention is well taken. I'll update. 
The const generic 'type' is indeed for performance reasons. I use my C# library for a game and perf is its primary limiting factor. In .NET I tend to allocate many of these objects on the heap and GC has been an issue. Maybe I'm over-optimizing too early in rust, so I may change this in the future.
